name: Auto clock-in

on:
  schedule:
    - cron: '0 8 * * 1-5' # Runs at 8:00 from monday to Friday
    - cron: '30 14 * * 1-5' # Runs at 14:30 from monday to Friday
    - cron: '30 15 * * 1' # Runs at 15:30 on monday
    - cron: '00 18 * * 1' # Runs at 18:00 on monday

# Get environment variables from the repository secrets
env:
  CLOCK_IN_USERNAME: ${{ secrets.CLOCK_IN_USERNAME }}
  CLOCK_IN_PASSWORD: ${{ secrets.CLOCK_IN_PASSWORD }}

jobs:
  fichaje:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install selenium

      - name: Run the script
        run: python script.py
